#!/usr/bin/env python3
from flask import Flask, render_template_string, request, send_file, jsonify
import google.generativeai as genai
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY
import os
from datetime import datetime
import re

app = Flask(__name__)

genai.configure(api_key="AIzaSyAJfmHfMHWMkZPR8aEgRqL_poa9v4zY3uM")

OUTPUT_DIR = 'generated_pdfs'
os.makedirs(OUTPUT_DIR, exist_ok=True)

def create_styled_pdf(content, topic, filename):
    pdf = SimpleDocTemplate(filename, pagesize=A4, rightMargin=50, leftMargin=50, topMargin=60, bottomMargin=50)
    elements = []
    styles = getSampleStyleSheet()

    title_style = ParagraphStyle('CustomTitle', parent=styles['Heading1'], fontSize=28, 
                                  textColor=colors.HexColor('#1a237e'), spaceAfter=30, 
                                  alignment=TA_CENTER, fontName='Helvetica-Bold', leading=34)
    
    subtitle_style = ParagraphStyle('CustomSubtitle', parent=styles['Heading2'], fontSize=16, 
                                     textColor=colors.HexColor('#455a64'), spaceAfter=12, 
                                     spaceBefore=20, fontName='Helvetica-Bold', 
                                     backColor=colors.HexColor('#e3f2fd'), leading=20)
    
    body_style = ParagraphStyle('CustomBody', parent=styles['BodyText'], fontSize=12, 
                                 textColor=colors.HexColor('#263238'), alignment=TA_JUSTIFY, 
                                 spaceAfter=14, spaceBefore=6, leading=18, fontName='Helvetica')
    
    info_style = ParagraphStyle('InfoStyle', parent=styles['Normal'], fontSize=10, 
                                 textColor=colors.HexColor('#607d8b'), alignment=TA_CENTER, 
                                 spaceAfter=30)
    
    footer_style = ParagraphStyle('FooterStyle', parent=styles['Normal'], fontSize=10, 
                                   textColor=colors.white, alignment=TA_CENTER)

    title_table = Table([[Paragraph(f"✨ {topic.upper()} ✨", title_style)]], colWidths=[450])
    title_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#e8eaf6')),
        ('BOX', (0, 0), (-1, -1), 2, colors.HexColor('#3f51b5')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 20),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 20),
    ]))
    elements.extend([title_table, Spacer(1, 20)])

    timestamp = datetime.now().strftime("%B %d, %Y at %I:%M %p")
    elements.extend([Paragraph(f"Generated by Gemini 2.5 Flash-Lite on {timestamp}", info_style), Spacer(1, 12)])

    line_table = Table([['', '']], colWidths=[225, 225])
    line_table.setStyle(TableStyle([
        ('LINEABOVE', (0, 0), (0, 0), 3, colors.HexColor('#ff6f00')),
        ('LINEABOVE', (1, 0), (1, 0), 3, colors.HexColor('#42a5f5')),
    ]))
    elements.extend([line_table, Spacer(1, 24)])

    paragraphs = re.split(r'\n\s*\n', content.strip())
    for para in paragraphs:
        para = para.strip()
        if not para:
            continue
        if para.startswith('## '):
            elements.append(Paragraph(f"📌 {para[3:].strip()}", subtitle_style))
        elif para.startswith('# '):
            elements.append(Paragraph(f"🔷 {para[2:].strip()}", subtitle_style))
        else:
            lines = para.split('\n')
            for line in lines:
                line = line.strip()
                if line.startswith(('•', '-')):
                    line = "▸ " + line[1:].strip()
                if line:
                    elements.append(Paragraph(line, body_style))
            elements.append(Spacer(1, 8))

    elements.append(Spacer(1, 30))
    footer_table = Table([[Paragraph("Created with Flask + Gemini 2.5 Flash-Lite + ReportLab 🚀", footer_style)]], colWidths=[450])
    footer_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#1976d2')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#0d47a1')),
        ('TOPPADDING', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
    ]))
    elements.append(footer_table)

    pdf.build(elements)
    return filename

HTML_TEMPLATE = '''
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Gemini 2.5 Flash-Lite PDF Generator</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            min-height: 100vh; padding: 20px; display: flex; justify-content: center; align-items: center;
        }
        .container { max-width: 600px; width: 100%; }
        .header { text-align: center; color: white; margin-bottom: 40px; }
        .header h1 { font-size: 2.5rem; margin-bottom: 10px; text-shadow: 2px 2px 4px rgba(0,0,0,0.3); }
        .subtitle { font-size: 1.1rem; opacity: 0.9; }
        .form-container { background: white; padding: 40px; border-radius: 20px; box-shadow: 0 20px 60px rgba(0,0,0,0.3); }
        .input-group { margin-bottom: 25px; }
        .input-group label { display: block; margin-bottom: 10px; font-weight: 600; color: #333; font-size: 1rem; }
        .input-group input {
            width: 100%; padding: 15px; border: 2px solid #e0e0e0; border-radius: 10px;
            font-size: 1rem; transition: all 0.3s ease;
        }
        .input-group input:focus { outline: none; border-color: #667eea; box-shadow: 0 0 0 3px rgba(102,126,234,0.1); }
        .btn-generate {
            width: 100%; padding: 16px; background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white; border: none; border-radius: 10px; font-size: 1.1rem; font-weight: 600;
            cursor: pointer; transition: transform 0.2s ease, box-shadow 0.2s ease;
        }
        .btn-generate:hover { transform: translateY(-2px); box-shadow: 0 10px 25px rgba(102,126,234,0.4); }
        .btn-generate:disabled { opacity: 0.7; cursor: not-allowed; }
        .spinner {
            display: inline-block; width: 16px; height: 16px; border: 3px solid rgba(255,255,255,0.3);
            border-radius: 50%; border-top-color: white; animation: spin 0.8s linear infinite; margin-right: 8px;
        }
        @keyframes spin { to { transform: rotate(360deg); } }
        .result-container, .error-container {
            margin-top: 30px; background: white; padding: 40px; border-radius: 20px;
            box-shadow: 0 20px 60px rgba(0,0,0,0.3); text-align: center;
        }
        .success-icon, .error-icon {
            width: 80px; height: 80px; border-radius: 50%; display: flex;
            align-items: center; justify-content: center; font-size: 3rem; margin: 0 auto 20px; color: white;
        }
        .success-icon { background: #4caf50; }
        .error-icon { background: #f44336; }
        .success-message h3, .error-message h3 { font-size: 1.5rem; margin-bottom: 10px; }
        .success-message p, .error-message p { margin-bottom: 20px; color: #666; }
        .btn-download {
            padding: 12px 30px; background: #4caf50; color: white; border: none; border-radius: 8px;
            font-size: 1rem; font-weight: 600; cursor: pointer; transition: all 0.3s ease;
        }
        .btn-download:hover { background: #45a049; transform: translateY(-2px); box-shadow: 0 5px 15px rgba(76,175,80,0.4); }
        @media (max-width: 768px) {
            .header h1 { font-size: 2rem; }
            .form-container, .result-container, .error-container { padding: 25px; }
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>⚡ Gemini 2.5 Flash-Lite PDF Generator</h1>
            <p class="subtitle">Ultra-fast AI-powered PDF creation</p>
        </div>
        <div class="form-container">
            <form id="pdfForm">
                <div class="input-group">
                    <label for="topic">Enter Your Topic or Prompt</label>
                    <input type="text" id="topic" placeholder="e.g., The Future of Artificial Intelligence" required>
                </div>
                <button type="submit" id="generateBtn" class="btn-generate">
                    <span class="btn-text">Generate PDF</span>
                    <span class="btn-loading" style="display: none;"><span class="spinner"></span> Generating...</span>
                </button>
            </form>
        </div>
        <div id="result" class="result-container" style="display: none;">
            <div class="success-message">
                <div class="success-icon">✓</div>
                <h3>PDF Generated Successfully!</h3>
                <p id="resultMessage"></p>
                <button id="downloadBtn" class="btn-download">Download PDF</button>
            </div>
        </div>
        <div id="error" class="error-container" style="display: none;">
            <div class="error-message">
                <div class="error-icon">✕</div>
                <h3>Error</h3>
                <p id="errorMessage"></p>
            </div>
        </div>
    </div>
    <script>
        document.getElementById('pdfForm').addEventListener('submit', async function(e) {
            e.preventDefault();
            const topic = document.getElementById('topic').value.trim();
            const generateBtn = document.getElementById('generateBtn');
            const btnText = generateBtn.querySelector('.btn-text');
            const btnLoading = generateBtn.querySelector('.btn-loading');
            const resultDiv = document.getElementById('result');
            const errorDiv = document.getElementById('error');
            resultDiv.style.display = 'none';
            errorDiv.style.display = 'none';
            generateBtn.disabled = true;
            btnText.style.display = 'none';
            btnLoading.style.display = 'inline-block';
            try {
                const response = await fetch('/generate-pdf', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ topic })
                });
                const data = await response.json();
                if (response.ok) {
                    document.getElementById('resultMessage').textContent = data.message;
                    document.getElementById('downloadBtn').onclick = () => {
                        window.location.href = '/download/' + data.filename;
                    };
                    resultDiv.style.display = 'block';
                } else {
                    document.getElementById('errorMessage').textContent = data.error || 'An error occurred';
                    errorDiv.style.display = 'block';
                }
            } catch (err) {
                document.getElementById('errorMessage').textContent = 'Network error: ' + err.message;
                errorDiv.style.display = 'block';
            } finally {
                generateBtn.disabled = false;
                btnText.style.display = 'inline-block';
                btnLoading.style.display = 'none';
            }
        });
    </script>
</body>
</html>
'''

@app.route('/')
def index():
    return render_template_string(HTML_TEMPLATE)

@app.route('/generate-pdf', methods=['POST'])
def generate_pdf():
    try:
        data = request.get_json()
        topic = data.get('topic', '').strip()
        if not topic:
            return jsonify({'error': 'Topic is required'}), 400

        model = genai.GenerativeModel("gemini-2.5-flash-lite")
        response = model.generate_content(f"""Write a comprehensive, well-structured article about: {topic}

        Format with:
        - Engaging introduction
        - Multiple sections with ## headings
        - Detailed explanations and examples
        - Key insights
        - Conclusion
        
        800-1200 words, professional tone.""")
        
        content = response.text

        safe_topic = re.sub(r'\W+', '_', topic)[:50]
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{safe_topic}_{timestamp}.pdf"
        filepath = os.path.join(OUTPUT_DIR, filename)

        create_styled_pdf(content, topic, filepath)

        return jsonify({'success': True, 'message': 'PDF generated successfully!', 'filename': filename})

    except Exception as e:
        return jsonify({'error': str(e)}), 500

@app.route('/download/<filename>')
def download_pdf(filename):
    try:
        file_path = os.path.join(OUTPUT_DIR, filename)
        if not os.path.exists(file_path):
            return jsonify({'error': 'File not found'}), 404
        return send_file(file_path, as_attachment=True, download_name=filename)
    except Exception as e:
        return jsonify({'error': str(e)}), 404

if __name__ == '__main__':
    print("⚡ Gemini 2.5 Flash-Lite PDF Generator Started!")
    print("📂 PDFs saved in:", os.path.abspath(OUTPUT_DIR))
    print("🌐 Open: http://127.0.0.1:5000")
    app.run(debug=True, host='127.0.0.1', port=5000)
